import { BadgeCheck, FileText, TriangleAlert } from 'lucide-react';
import type { ImpactAssessment } from '@/api/types';
import { cn } from '@/lib/cn';

/**
 * Who wrote this advisory, and how long they took.
 *
 * Three states, deliberately distinguishable at a glance rather than blended into one "AI-powered"
 * badge: written by the model, written by the template because no model is configured, and written
 * by the template because the model was attempted and failed. The third is the one that matters
 * operationally — an operator reading a warning needs to know a model was supposed to write it and
 * did not, because that is a deployment problem they can report.
 *
 * The tooltip carries the server's own explanation, so a degraded chip can be diagnosed without
 * opening a log file.
 */
export function ProvenanceChip({
  assessment,
  className,
}: {
  assessment: ImpactAssessment;
  className?: string;
}) {
  const provenance = assessment.advisoryProvenance;

  if (provenance.generator === 'gemini' && !provenance.degraded) {
    return (
      <span
        title={provenance.detail ?? undefined}
        className={cn('badge bg-brand-50 text-brand-700 ring-brand-200', className)}
      >
        <BadgeCheck className="size-3.5" />
        Generated by {provenance.model ?? 'Gemini'} · {provenance.latencyMillis} ms
      </span>
    );
  }

  if (provenance.degraded) {
    return (
      <span
        title={provenance.detail ?? undefined}
        className={cn('badge bg-amber-50 text-amber-800 ring-amber-200', className)}
      >
        <TriangleAlert className="size-3.5" />
        Deterministic fallback · model unavailable
      </span>
    );
  }

  return (
    <span
      title={provenance.detail ?? undefined}
      className={cn('badge bg-ink-100 text-ink-600 ring-ink-200', className)}
    >
      <FileText className="size-3.5" />
      Deterministic generator
    </span>
  );
}
